### ISSUE TITLE
Unable to place a different core when removing old core

### ISSUE THREAD

**Issue by Arkaiser85** [DraconisCluster/DracVerse-Issues#17] opened 2022-05-07 17:19 UTC
Removing the basic core from a grid prevents you from placing a different core, like a utility core unless you do !fixship
On DV6

**Comment by Synirrr** [comment] 2022-05-22 17:51
Duplicate of [Issue44](https://github.com/DraconisCluster/DracVerse-Issues/issues/44)

**Closed by Synirrr** 2022-05-22 17:51 UTC
Labels: bug, duplicate
