### ISSUE TITLE
Cores not functioning well

### ISSUE THREAD

**Issue by Joyfulasteroid** [DraconisCluster/DracVerse-Issues#20] opened 2022-05-07 23:18 UTC
Description:

Trying to just play a normal playthrough. 

Constantly having to fixship the grid to be able to place blocks. Sometimes placing a new block causes the core to have an issue with a block thats been on there for a while. 

Grid cores are not documented and are just causing constant issues with grids.

To reproduce:
1) Place ground station core (not tested with others yet)
2) place blocks
3) Wait around 10 mins
4) try to place block and grid denies it

Workaround:
Fixship the grid and hope it doesn't make the core hate you

Instanace: DV7

**Comment by kontu** [comment] 2022-05-11 16:32
Testing today with basic cores and ground station cores I was unable to reproduce this issue. 20 minutes after building my grid I was still able to place on it no problem

**Comment by plutothemad** [comment] 2022-05-11 21:49
not fixed for spaceships, added a new bug ticket

**Comment by Synirrr** [comment] 2022-05-22 18:00
Fixed with latest update of cores

**Closed by Synirrr** 2022-05-22 18:00 UTC
Labels: bug
